User.create(username: "jsingleton", email: "jsingleton@test.com", password: "123pass")
User.create(username: "egnelson", email: "egnelson@test.com", password: "pass123")

Lawyer.create(name: "Mickey", LGBTQ_friendly?: "yes", phone_number: "111-111-1111", address: "123 Cat St, Catsville, MN 55555", website: "www.catzcanhelp.com", cost: "reduced-fee")
Lawyer.create(name: "Roger Barton", LGBTQ_friendly?: "not verified", phone_number: "222-222-2222", address: "345 Tomcat Alley, Tigertown, MN 44444", website: "www.catzrtuff.com", cost: "private")
Lawyer.create(name: "Loverboi", LGBTQ_friendly?: "yes", phone_number: "333-333-3333", address: "567 Catnip Ave, Kittenapolis, MN 66666", website: "www.purrs.com", cost: "free")

Practice_area.create(name: "Family Law")
Practice_area.create(name: "Employment Law")
Practice_area.create(name: "Housing Law")
Practice_area.create(name: "Public Benefits Law")
Practice_area.create(name: "Health Law")
Practice_area.create(name: "Consumer Law")

Lawyer_practice_area.create(lawyer_id: "1", practice_area_id: "1")
Lawyer_practice_area.create(lawyer_id: "1", practice_area_id: "3")
Lawyer_practice_area.create(lawyer_id: "1", practice_area_id: "5")
Lawyer_practice_area.create(lawyer_id: "2", practice_area_id: "2")
Lawyer_practice_area.create(lawyer_id: "2", practice_area_id: "6")
Lawyer_practice_area.create(lawyer_id: "3", practice_area_id: "1")
Lawyer_practice_area.create(lawyer_id: "3", practice_area_id: "3")
Lawyer_practice_area.create(lawyer_id: "3", practice_area_id: "4")
Lawyer_practice_area.create(lawyer_id: "3", practice_area_id: "6")
