User.create(username: "jsingleton", email: "jsingleton@test.com", password: "123pass")
User.create(username: "egnelson", email: "egnelson@test.com", password: "pass123")

Lawyer.create(name: "Mickey", LGBTQ_friendly?: "yes", phone_number: "111-111-1111", website: "www.catzcanhelp.com", cost: "reduced-fee")
Lawyer.create(name: "Roger Barton", LGBTQ_friendly?: "not verified", phone_number: "222-222-2222", website: "www.catzrtuff.com", cost: "private")
Lawyer.create(name: "Loverboi", LGBTQ_friendly?: "yes", phone_number: "333-333-3333", website: "www.purrs.com", cost: "free")

PracticeArea.create(name: "Family Law")
PracticeArea.create(name: "Employment Law")
PracticeArea.create(name: "Housing Law")
PracticeArea.create(name: "Public Benefits Law")
PracticeArea.create(name: "Health Law")
PracticeArea.create(name: "Consumer Law")

LawyerPracticeArea.create(lawyer_id: "1", practice_area_id: "1")
LawyerPracticeArea.create(lawyer_id: "1", practice_area_id: "3")
LawyerPracticeArea.create(lawyer_id: "1", practice_area_id: "5")
LawyerPracticeArea.create(lawyer_id: "2", practice_area_id: "2")
LawyerPracticeArea.create(lawyer_id: "2", practice_area_id: "6")
LawyerPracticeArea.create(lawyer_id: "3", practice_area_id: "1")
LawyerPracticeArea.create(lawyer_id: "3", practice_area_id: "3")
LawyerPracticeArea.create(lawyer_id: "3", practice_area_id: "4")
LawyerPracticeArea.create(lawyer_id: "3", practice_area_id: "6")
